// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB287P9XZHLTDGKS4TDMt26cTXcmCAMhAI',
    appId: '1:1078650493828:web:c0831c610d728712ec1bd1',
    messagingSenderId: '1078650493828',
    projectId: 'contactfirebase-248c8',
    authDomain: 'contactfirebase-248c8.firebaseapp.com',
    storageBucket: 'contactfirebase-248c8.appspot.com',
    measurementId: 'G-NFWCSYYVRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeQkUehbwP5Drt1GeYUlY9UkPqRmIrvo',
    appId: '1:1078650493828:android:97d527f262cabec3ec1bd1',
    messagingSenderId: '1078650493828',
    projectId: 'contactfirebase-248c8',
    storageBucket: 'contactfirebase-248c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8b9fiTKI2aFbKEaFx5DL6J-7WEUxwpDE',
    appId: '1:1078650493828:ios:2f5f49fc2daeae60ec1bd1',
    messagingSenderId: '1078650493828',
    projectId: 'contactfirebase-248c8',
    storageBucket: 'contactfirebase-248c8.appspot.com',
    iosBundleId: 'com.example.flutterContactFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8b9fiTKI2aFbKEaFx5DL6J-7WEUxwpDE',
    appId: '1:1078650493828:ios:2f5f49fc2daeae60ec1bd1',
    messagingSenderId: '1078650493828',
    projectId: 'contactfirebase-248c8',
    storageBucket: 'contactfirebase-248c8.appspot.com',
    iosBundleId: 'com.example.flutterContactFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB287P9XZHLTDGKS4TDMt26cTXcmCAMhAI',
    appId: '1:1078650493828:web:e06578208bf0a8c8ec1bd1',
    messagingSenderId: '1078650493828',
    projectId: 'contactfirebase-248c8',
    authDomain: 'contactfirebase-248c8.firebaseapp.com',
    storageBucket: 'contactfirebase-248c8.appspot.com',
    measurementId: 'G-04KMSQRXT8',
  );
}
